### ISSUE TITLE
Setting Constraints

### ISSUE THREAD

**Issue by sara-shahin-cell** [MIT-Emerging-Talent/ET6-foundations-group-21#2]
Constraints
We are facing several challenges that are impacting the project's progress. These challenges are classified into external and internal issues.

External:
Behavior: limited internet access, and personal issues (e.g., family responsibilities, and health challenges) are hindering collaboration and progress.
Internal: Involuntary:
Behavior: team conflicts are causing delays in the workflow. Personal challenges faced by team members are also affecting productivity.
Internal: Voluntary:
Behavior: Some decisions made by the team, like prioritizing certain tasks or adapting workflows, are contributing to delays or inefficiencies. These voluntary decisions may need reassessment for better project flow.

**Comment by Fikre-Mamo** [comment]
Hi Nour,

Thank you for sharing the challenges you're facing. I understand that both external and internal factors can significantly impact progress. Let's work together to address these issues effectively.

For external challenges (e.g., internet access, personal responsibilities):
If there’s anything specific that can help, such as flexible deadlines or alternative resources, let me know, and we’ll explore feasible solutions.

For internal issues (e.g., team conflicts or workflow challenges):
I encourage open communication to address conflicts constructively. If there’s a particular conflict or workflow issue you think we should focus on, please share your thoughts. We can work as a team to find solutions that improve collaboration and efficiency.

For voluntary decisions impacting the project:
If you have suggestions on how we can reassess priorities or workflows, I’d love to hear them. Your insights are valuable in creating a smoother project flow.

we are here to support you and each other, so please don’t hesitate to share more details or let us know so we can assist each other. Together, we’ll overcome these challenges and keep moving forward.

**Comment by sara-shahin-cell** [comment]
Hello @Fikre-Mamo I didn't add my constraint yet. I just created this Issue for all of us to share our constraints as part of our task. So Each of us in the group is supposed to add his/her constraints here.  
I just clarified what kind of constraints we could add as it is mentioned in the [constraints ](https://github.com/MIT-Emerging-Talent/ET6-foundations-group-21/blob/main/collaboration/constraints.md ).
So please add your own constraints here as a comment. Thanks

**Comment by Solarahamza** [comment]
Hello guys,

These are my constraints
External Constraints
	•	Work obligations: I work for an organization and it can get very demanding at times mentally and time-wise
	•	Time difference between participants: This has led me to miss a meeting
Involuntary Internal Constraints
	•	Studying for an exam: This is an imp exam in my career and currently trying to balance the time between studying for MIT, for the exam and work all together
	•	Taking care of my family: I'm currently living with my parents which is a blessing but it also comes with its chores as they depend on me
Voluntary Internal Constraints
	•	Would appreciate it if when we agree on a meeting time, we give at least 24 hours notice so that none of us gets left clueless about what's going on

**Comment by sara-shahin-cell** [comment]
My constraints are:
External
Limited Internet Access: Unexpected internet outages caused by nearby construction occasionally disrupt my ability to work efficiently.
Family Responsibilities: My productivity tends to slow down during weekends due to family commitments.
Internal
Involuntary
Stress: Balancing multiple responsibilities has sometimes affected my efficiency and focus.
Voluntary
None at the moment.

**Comment by Fikre-Mamo** [comment]
My Constraints are:

**1- External Constraints**:
**Internet Connectivity Issues**: Occasional disruptions due to local service outages may impact online communication.
**Time Zone Differences:** Coordinating with team members in different regions can sometimes delay responses.

**2- Internal Constraints:**

**Involuntary:** 
**Family Responsibilities:** Balancing family obligations, especially during evenings and weekends, can reduce my availability.
**Workload from Other Commitments**: Managing overlapping deadlines from work or personal projects might limit my focus temporarily.

**3- Voluntary:**
None at the moment

**Comment by omerdafaalla** [comment]
Hi @Solarahamza 


   Thanks for sharing your constraints

  For work and study obligations , maybe we can agree on a fixed, shorter meeting schedule to reduce time  while ensuring 
  productivity.
  Regarding the 24-hour notice for meetings, I fully support this suggestion, It will help ensure everyone can prepare and 
  attend.
  Regarding the time differences, since our meeting are recorded , you can always watch the recording at a convenient time .

  Let me know what you think about these ideas

**Comment by omerdafaalla** [comment]
My Constraints are :

1. External Constraints:
Work commitments: High workload and tight deadlines.
Time zone difference: Challenges in coordinating with team members due to time gaps.

2. Internal Constraints:
Involuntary:
Family responsibilities: Balancing family obligations, supporting family members reduces availability during evenings and weekends.
Study: Preparing for an important career-related exam along with other commitments.

3. Voluntary Constraints:
None at the moment

**Comment by collyns-linc** [comment]
Hello Team,

I’d like to share some constraints that are currently affecting my participation in our project:

### External Constraints:
- My internet connection has been poor over the holiday, which has impacted my ability to actively participate in the team project.
- My computer has developed some complications. I am addressing this and plan to fix it within the week.
- Balancing family responsibilities with the project has been challenging during this holiday period.
### Internal Constraints (Involuntary):
- I have university exams next month, which require advance preparation. I am working on balancing my study time with my contributions to the MIT team project.
### Internal Constraints (Voluntary):
- I find our team communication and decision-making processes a bit unclear at times.
- Short notice for meetings makes it difficult for me to collaborate effectively, as I am not always online.


I appreciate your understanding and support as I navigate these challenges. Please let me know if there are adjustments or alternatives we can consider to help improve collaboration during this period.

**Comment by AmmarIbrahimTech** [comment]
# Group 21 Constraints

## External Constraints

- **Time Zone Differences**: {~Solarahamza, Nouranaia, Omerdafaalla}  
- **Family Responsibilities**: {~Nouranaia, Fikre-Mamo, Omerdafaalla, Collins Ochieng}  
- **Work Obligations**: {~Solarahamza, Fikre-Mamo, Omerdafaalla, Ammar}  
- **Studying for Exams**: {~Solarahamza, Omerdafaalla, Collins Ochieng, Ammar}  
- **Limited Internet Access**: {~Nouranaia, Fikre-Mamo, Collins Ochieng}  
- **Device Issues (Computer Complications)**: {~Collins Ochieng}  

---

## Involuntary Internal Constraints

- **Stress Balancing Multiple Responsibilities**: {~Nouranaia}  
- **Likes to Take Responsibility and Lead**: {~Ammar}  
  _(May be annoying sometimes, so notify me if it feels like I'm taking over too much.)_  
- **No Past Experience in Coding**: {~Ammar}  

---

## Voluntary Internal Constraints

- **None at the moment**  

---

## Suggested Group Norm
- **Meeting Time Notice**: Most members suggested that we agree on meeting times at least 24 hours in advance. This should be added to the group norms.

**Comment by sara-shahin-cell** [comment]
Thanks, Everyone
