### ISSUE TITLE
Setting Group Norms

### ISSUE THREAD

**Issue by Solarahamza** [MIT-Emerging-Talent/ET6-foundations-group-21#4]
Setting Group Norms
How can you build and maintain Cognitive & Affective trust?
What can you do if that trust is damaged?
How does your team want to balance Discussion & Debate? When is one more appropriate than the other?
How will your team approach meeting times and agendas?
How and where do you want to communicate about different aspects of the project?
What makes you feel respected? Or disrespected?
… dig deep in your memory and your imagination - what else could be important? 

https://docs.google.com/document/d/1RaPP8CWzTwvniiuXpTnnnSohWCHx5M4mm-ST24aPYBk/edit?tab=t.0
https://docs.google.com/presentation/d/1IbHkR37KBSACvWiMLX41juLqrcV4OxTrARSsXKqv1aA/edit#slide=id.g2adaa6a7ff8_0_40

**Comment by Fikre-Mamo** [comment]
## 1. How can we build and maintain Cognitive & Affective trust?
### Cognitive Trust:

- Deliver work on time and follow through on commitments.
- Be transparent about progress, challenges, and potential delays.
- Share expertise and help others when needed.

### Affective Trust:

- Show empathy and understanding for teammates' situations.
- Celebrate each other's successes and acknowledge efforts.
- Foster open, non-judgmental communication to create a safe environment.

## 2. What can you do if that trust is damaged?

- Address issues as soon as they arise, directly and respectfully.
- Acknowledge the problem and take responsibility where necessary.
- Discuss solutions collaboratively and agree on actionable steps to rebuild trust.
- Commit to regular check-ins to ensure progress and avoid further misunderstandings.


## 3. How does your team want to balance Discussion & Debate?

### Use Discussion:
- For brainstorming, sharing ideas, and building consensus.
- When the team needs creative solutions or is in the early stages of problem-solving.

### Use Debate:
- For analyzing and deciding between conflicting options.
- When critical decisions need logical reasoning and evidence-based arguments.

### Guidelines:
- Maintain respect and focus on the problem, not the person.
- Be clear on the goal of each conversation: Are you exploring ideas or making decisions?


## 4. How will your team approach meeting times and agendas?

- Schedule meetings at regular intervals that suit all members.
- Keep meetings short and focused (e.g., under 30 minutes).
- Share an agenda at least 24 hours before the meeting.
- Assign a timekeeper to ensure the meeting stays on track.
- Conclude with a summary of action items and deadlines.

## 5. How and where do you want to communicate about different aspects of the project?

- Use a team communication tool (Slack) for daily updates.
- Microsoft Teams for meeting
- Discuss project tasks and track progress on **GitHub Issues** or a **GitHub Project**
- Use **Email** or formal documentation for external communication or major updates.
- **Tag relevant teammates** and categorize messages to avoid confusion.

## 6. What makes you feel respected? Or disrespected?

### Respectful Actions:

- Actively listening and valuing everyone’s opinions.
- Giving credit for individual contributions.
- Offering constructive feedback instead of criticism.

### Disrespectful Actions:

- Ignoring input or dominating conversations.
- Missing deadlines without explanation.
- Making personal or unkind remarks during discussions.

## 7. Additional Considerations
### Work-Life Balance:

- Define clear work hours to avoid burnout.
- Respect boundaries during weekends or off-hours.

### Feedback:

- Create a safe space for giving and receiving feedback.
- Focus on improvement rather than fault-finding.

### Inclusivity:

- Ensure everyone has an equal chance to contribute, especially during discussions.
- Rotate responsibilities, such as meeting facilitation, to distribute ownership.

**Comment by Tahershaba** [comment]
Considerations for Group Norms


Define a clear process for resolving disagreements


Encourage regular, constructive feedback (both giving and receiving).




Actively create an environment where all voices are valued and heard.


Promote work-life balance and support each other during high-stress periods.

**Comment by Solarahamza** [comment]
How can you build and maintain cognitive and affective trust?

Trust grows when team members demonstrate reliability and commitment. Cognitive and affective trust can be built and maintained by consistently working together, showing up for one another, and delivering on assigned tasks.

What can you do if that trust is damaged?
If trust is damaged, the first step is to acknowledge the issue and take responsibility for what went wrong. Following that, we can work to rebuild trust by committing to change, demonstrating specific actions that reflect this change, and maintaining open communication to avoid future misunderstandings.

How does your team want to balance discussion and debate? When is one more appropriate than the other?
When discussions turn into debates, it’s important to pause, reassess, and possibly seek a third party’s input to mediate. Trust and a willingness to compromise for the team’s unity are key to balancing the two. Discussion is more appropriate for collaborative problem-solving, while debate may be helpful when evaluating differing viewpoints to reach the best decision.

How will your team approach meeting times and agendas?
Our team will use polls to determine meeting times and agendas. The poll will allow all members to vote, and the most voted time and date will be selected. To ensure everyone has time to prepare, polls will be conducted at least 24 hours before the proposed meeting time

How and where do you want to communicate about different aspects of the project?
It has already been agreed that project communications will take place on Slack for discussions and GitHub for issue tracking and project-specific updates.

What makes you feel respected or disrespected?
I feel respected when my time is valued and people are considerate of it. On the other hand, I feel disrespected when I feel invisible or unacknowledged.

**Comment by sara-shahin-cell** [comment]
Some Considerations for Group Norms:
Flexibility: Recognizing and being empathetic toward personal situations and challenges. Understanding that people have different working styles and schedules.
Cultural Sensitivity: Being aware of cultural differences and making an effort to include everyone in a way that respects their backgrounds and perspectives.
Feedback Culture: Establishing a constructive feedback loop where feedback is regularly given and received for continuous improvement.
Celebrating Milestones: Celebrate project wins, big or small, to maintain morale and foster a sense of achievement.
